name: Build and Push Docker Images

on:
  workflow_dispatch:  # Allows you to manually trigger the action from the Actions tab
  push:  # Automatically triggers on every commit to the main branch
    branches:
      - master  # Replace with the branch you want to monitor, e.g., 'main' or 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Clone the repository and get the latest commit
      - name: Get Latest Commit
        id: latest_commit
        run: |
          git clone https://git.streamboard.tv/common/oscam.git || true
          cd oscam || true
          LATEST_COMMIT=$(git rev-parse HEAD || true)

          # Check if LATEST_COMMIT is empty
          if [ -z "$LATEST_COMMIT" ]; then
            echo "Failed to fetch latest commit. Exiting gracefully."
            exit 0
          fi

          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_ENV

      # Set up QEMU for emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build and push multi-arch images
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            chris230291/ncam:${{ env.latest_commit }}
            chris230291/ncam:latest
