name: Check for Patch Updates and Build Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Check every day at midnight
  workflow_dispatch:  # Allow manual triggering from the Actions tab

jobs:
  check-for-patch:
    runs-on: ubuntu-latest
    outputs:
      patch_changed: ${{ steps.check.outputs.patch_changed }}

    steps:
      - name: Clone external repository
        run: |
          # Clone the external repo and check out the specific file
          git clone --depth=1 https://github.com/oscam-emu/oscam-emu.git external_repo
          cp external_repo/oscam-emu.patch ./oscam-emu.patch

      - name: Attempt to download previous patch artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: previous_patch  # Name of the artifact to download
          path: ./  # Download to current working directory
        continue-on-error: true  # Continue even if the artifact does not exist

      - name: Check for changes in oscam-emu.patch
        id: check
        run: |
          # Create a temporary file to compare against
          if [[ -f previous_patch.patch ]]; then
            # If previous version exists, compare it
            if ! diff -q previous_patch.patch oscam-emu.patch; then
              echo "File has changed."
              echo "::set-output name=patch_changed::true"
            else
              echo "File has not changed."
              echo "::set-output name=patch_changed::false"
            fi
          else
            # If no previous version, consider it changed
            echo "No previous patch found. Treating as changed."
            echo "::set-output name=patch_changed::true"
          fi

      - name: Upload current patch as artifact
        if: steps.check.outputs.patch_changed == 'true'  # Only upload if it changed
        uses: actions/upload-artifact@v3
        with:
          name: previous_patch  # Name of the artifact to save
          path: oscam-emu.patch  # Path to the current patch

  build:
    runs-on: ubuntu-latest
    needs: check-for-patch
    if: needs.check-for-patch.outputs.patch_changed == 'true'  # Only run if the file has changed

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Set up QEMU for emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push multi-arch images
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: chris230291/oscam-emu:latest
